const MODULE_ID = '@DEATHS/';

export const CALLING_DEATHS = MODULE_ID + 'CALLING DEATHS';
export const CALLED_DEATHS_SUCCESS = MODULE_ID + 'CALLED DEATH SUCCESS';
export const CALLED_DEATHS_FAILED  = MODULE_ID + 'CALLED DEATH FAILED';
