const MODULE_ID = '@QUOTES/';

export const CALLING_QUOTES_CHARACTER = MODULE_ID + 'CALLING CHARACTERS QUOTES';
export const CALLED_QUOTES_CHARACTER_SUCCESS = MODULE_ID + 'CALLED CHARACTERS SUCCESS';
export const CALLED_QUOTES_CHARACTER_FAILED = MODULE_ID + 'CALLED CHARACTERS FAILED';
